import type { RuleId } from "../../../server/rules";

/** Spanish one-liners for the agent console and trace view (audience: bank staff and judges). */
export const RULE_TEXT: Record<RuleId, string> = {
  IN_EMPTY: "Mensaje vacío o inválido",
  IN_SIZE: "Mensaje demasiado largo",
  IN_RATE: "Límite de mensajes por minuto",
  IN_AUTH_001: "Credenciales de demo inválidas",
  IN_AUTH_002: "Token inválido",
  IN_SESSION_EXPIRED: "Sesión expirada",
  IN_SESSION_REVOKED: "Sesión cerrada o no activa",
  IN_INJECTION: "Señal de inyección de instrucciones",
  IN_ROLE: "Rol no autorizado para esta ruta",
  IN_THREAD: "threadId distinto a la sesión",
  BUD_TURNS: "Límite de turnos por sesión",
  BUD_TOKENS: "Límite de tokens por sesión",
  BUD_SPEND: "Límite de gasto diario",
  BUD_SESSION: "Presupuesto de sesión agotado",
  BUD_CALLS: "Límite de llamadas LLM por turno",
  BUD_SAFE_MODE: "SAFE_MODE: sin llamadas al modelo",
  BUD_BREAKER: "Circuito del proveedor abierto",
  BUD_PROVIDER: "Error del proveedor LLM",
  BUD_TOTAL: "Tope total de gasto LLM del proyecto",
  RT_LOW_CONFIDENCE: "Confianza del router bajo el umbral: se pide aclaración",
  RT_OUT_OF_SCOPE: "Fuera de alcance: se abstiene",
  SC_INVALID: "Salida del modelo no cumple el esquema",
  POL_STATUS: "Cliente suspendido o cerrado: humano",
  POL_HUMAN: "El cliente pidió un humano",
  POL_RISK: "Riesgo de sesión acumulado: humano",
  POL_SCOPE: "Intención fuera de la política",
  POL_READ: "Consulta de solo lectura permitida",
  POL_DSP_NO_TARGET: "No se identificó la transacción",
  POL_DSP_MANY: "3 o más transacciones en disputa: humano",
  POL_DSP_AMOUNT: "Monto sobre 250 USD: humano",
  POL_DSP_FRAUD: "fraud_score ≥ 30: posible fraude, humano",
  POL_DSP_STATUS: "La transacción no está aprobada",
  POL_DSP_TYPE: "Tipo de transacción no disputable",
  POL_DSP_AGE: "Transacción con más de 90 días",
  POL_DSP_DUP: "Transacción ya disputada",
  POL_DSP_OK: "Disputa automática permitida (requiere confirmación)",
  POL_REPEAT: "Reclamante frecuente: humano",
  PROV_001: "Dato de origen no confiable para esta acción",
  TL_FAIL: "Falla de herramienta tras reintentos",
  TL_NOT_FOUND: "Registro no encontrado",
  TL_OWNER: "El registro no pertenece al cliente",
  TL_EMPTY: "La consulta no devolvió resultados",
  TL_BAD_INPUT: "Entrada inválida para la herramienta",
  TL_IDEMPOTENCY_MISMATCH: "Clave de idempotencia con otro contenido",
  TL_NOT_DISPUTABLE: "Transacción no disputable",
  TL_ALREADY_DISPUTED: "Transacción ya disputada",
  TL_NONCE_UNKNOWN: "Confirmación desconocida",
  TL_NONCE_USED: "Confirmación ya usada",
  TL_NONCE_EXPIRED: "Confirmación vencida",
  TL_NONCE_MISMATCH: "Confirmación no corresponde a la acción",
  VF_READBACK: "El caso creado no se pudo verificar",
  RS_CANARY: "Fuga del token canario en la respuesta",
  RS_PII: "Dato personal en la respuesta",
  RS_ID: "Id no respaldado por los datos",
  RS_AMOUNT: "Monto no respaldado por los datos",
  RS_COMMIT: "Compromiso fuera de plantilla",
  RS_LANG: "Idioma de respuesta incorrecto",
  RS_CITE: "Respuesta sin citar transacciones",
  RSK_SESSION: "Umbral de riesgo de sesión",
};

export const ruleText = (id: string): string => (RULE_TEXT as Record<string, string>)[id] ?? id;
