-- AIDO schema on Postgres (Supabase). Two schemas, neither exposed through the Supabase Data API:
--   serving: read-only customer subset built by the pipeline (or the demo seed)
--   ops:     writable runtime state (sessions, disputes, handoffs, nonces, audit, spans, checkpoints)
-- Every statement is idempotent: the server applies this file at startup and `supabase db push` tracks it too.
-- Timestamps are ISO-8601 text on purpose: the policy engine, audit hash chain and tests compare exact strings.

create schema if not exists serving;
create schema if not exists ops;

-- ── serving ────────────────────────────────────────────────────────────────────────────────────────────────
create table if not exists serving.customers (
  customer_id text primary key, first_name text, last_name text, country text, segment text,
  customer_status text, detected_accent text, source_file text, load_id text);

create table if not exists serving.products (
  product_id text primary key, customer_id text not null, product_type text, product_number_masked text,
  currency text, current_balance double precision, credit_limit double precision, product_status text,
  source_file text, load_id text);

create table if not exists serving.transactions (
  transaction_id text primary key, transaction_date text not null, product_id text, customer_id text not null,
  transaction_type text, transaction_category text, amount double precision, currency text,
  amount_usd double precision, channel text, merchant_name text, merchant_category text,
  transaction_country text, transaction_city text, transaction_status text, response_code text,
  fraud_score double precision, source_file text, load_id text);

create table if not exists serving.complaints (
  complaint_id text primary key, customer_id text not null, creation_date text, category text, subcategory text,
  status text, claimed_amount double precision, currency text, is_repeat_complainer integer not null default 0,
  affected_product_id text, source_file text, load_id text);

create table if not exists serving.demo_users (persona text primary key, customer_id text not null);
create table if not exists serving.meta (key text primary key, value text);

create index if not exists idx_products_customer on serving.products (customer_id);
create index if not exists idx_transactions_customer_date on serving.transactions (customer_id, transaction_date desc);
create index if not exists idx_complaints_customer on serving.complaints (customer_id);

-- ── ops ────────────────────────────────────────────────────────────────────────────────────────────────────
create table if not exists ops.sessions (
  session_id text primary key, customer_id text, role text not null, language text not null,
  created_at text not null, expires_at text not null, status text not null default 'active',
  risk_score double precision not null default 0, turns integer not null default 0,
  tokens integer not null default 0);

create table if not exists ops.disputes (
  dispute_id text primary key, idempotency_key text not null unique, session_id text not null,
  customer_id text not null, transaction_ids text not null, reason text not null, customer_note text,
  note_untrusted integer not null default 1, amount_usd double precision not null, status text not null,
  created_at text not null, payload_hash text);
create index if not exists idx_disputes_customer on ops.disputes (customer_id);

create table if not exists ops.handoffs (
  handoff_id text primary key, idempotency_key text unique, payload_hash text, session_id text not null,
  customer_id text not null, rule_ids text not null, card text not null, status text not null default 'queued',
  created_at text not null, taken_by text, resolved_at text);
create index if not exists idx_handoffs_status on ops.handoffs (status, created_at);

create table if not exists ops.nonces (
  nonce text primary key, session_id text not null, interrupt_id text not null, payload_hash text not null,
  expires_at double precision not null, used_at double precision);

create table if not exists ops.audit_events (
  seq integer generated by default as identity primary key, at text not null, session_id text,
  kind text not null, rule_id text, payload text not null, prev_hash text not null, hash text not null);

create table if not exists ops.spans (
  ord integer generated by default as identity, span_id text primary key, trace_id text not null,
  session_id text not null, parent_id text, name text not null, started_at text not null,
  duration_ms double precision not null, attributes text not null);
create index if not exists idx_spans_session on ops.spans (session_id, started_at, ord);

create table if not exists ops.spend (day text primary key, usd double precision not null default 0);

create table if not exists ops.rate_events (session_id text not null, at_ms double precision not null);
create index if not exists idx_rate_events_session on ops.rate_events (session_id, at_ms);

create table if not exists ops.messages (
  id integer generated by default as identity primary key, session_id text not null, author text not null,
  text text not null, at text not null);
create index if not exists idx_messages_session on ops.messages (session_id, id);

-- LangGraph checkpoints (same layout as the official savers).
create table if not exists ops.checkpoints (
  thread_id text not null, checkpoint_ns text not null default '', checkpoint_id text not null,
  parent_checkpoint_id text, type text, checkpoint bytea, metadata bytea,
  primary key (thread_id, checkpoint_ns, checkpoint_id));

create table if not exists ops.writes (
  thread_id text not null, checkpoint_ns text not null default '', checkpoint_id text not null,
  task_id text not null, idx integer not null, channel text not null, type text, value bytea,
  primary key (thread_id, checkpoint_ns, checkpoint_id, task_id, idx));
